version: '3.8'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - ./vault/scripts:/vault/scripts
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    command: [ "vault", "server", "-dev" ]

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sap_subsystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/initSql/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d sap_subsystem" ]
      interval: 5s
      retries: 5
      start_period: 10s
  app:
    build: .
    container_name: sap_subsystem_spring_boot_app
    ports:
      - "${SERVER_PORT}:8081"
    environment:
      - GITHUB_API_URL=https://api.github.com
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - VAULT_ADDR=http://vault-server:8200
      - VAULT_TOKEN=root
      - SERVER_PORT=8081
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
  vault_data:
