spring:
    application:
        name: subsystem
    datasource:
        url: jdbc:h2:mem:sap_subsystem
        driver-class-name: org.h2.Driver
        username: root
        password: pass
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
    liquibase:
        change-log: classpath:db/liquibase-changelog.xml

