server:
  port: 8081

spring:
  application:
    name: subsystem
  datasource:
    url: jdbc:postgresql://localhost:5432/sap_subsystem
    driver-class-name: org.postgresql.Driver
    username: root
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml

github:
  api_url: https://api.github.com
  token: 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
  owner: traxaz