server:
  port: 8081

spring:
  application:
    name: subsystem
  datasource:
    url: jdbc:postgresql://localhost:5432/sap_subsystem
    driver-class-name: org.postgresql.Driver
    username: root
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml

github:
  api_url: ${GITHUB_API_URL:https://api.github.com}
  token: ${GITHUB_ACCESS_TOKEN}
  owner: ${GITHUB_OWNER}

